In [4]:
import numpy as np

class ReLU():
    def forward(self, input):
        return np.maximum(0, input)
    
    def backward(self, input, output_gradient):
        grad = input > 0
        return grad * output_gradient

# ReLU 클래스 인스턴스 생성
relu = ReLU()

# 입력 데이터 생성
input_data = np.array([-2, -1, 0, 1, 2])

# Forward pass (ReLU 활성화 함수 적용)
output = relu.forward(input_data)
print("Forward output:", output)

# 가상의 output gradient (역전파 단계에서 전달되는 gradient)
output_gradient = np.array([1, 1, 1, 1, 1])

# Backward pass (ReLU의 기울기 계산)
input_gradient = relu.backward(input_data, output_gradient)
print("Backward output (input gradients):", input_gradient)

Forward output: [0 0 0 1 2]
Backward output (input gradients): [0 0 0 1 1]


In [7]:
import numpy as np

x = np.array(([1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]))

# 개선된 Softmax 함수
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

print(softmax(x))  # 안정적인 결과


[[2.12078996e-04 5.76490482e-04 1.56706360e-03]
 [4.25972051e-03 1.15791209e-02 3.14753138e-02]
 [8.55587737e-02 2.32572860e-01 6.32198578e-01]]
